// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: tablereservation.proto

package grpc.ca.tablereservation;

public interface CancelRequestOrBuilder extends
    // @@protoc_insertion_point(interface_extends:tablereservation.CancelRequest)
    com.google.protobuf.MessageOrBuilder {

  /**
   * <code>int32 resID = 1;</code>
   */
  int getResID();

  /**
   * <code>string name = 2;</code>
   */
  java.lang.String getName();
  /**
   * <code>string name = 2;</code>
   */
  com.google.protobuf.ByteString
      getNameBytes();

  /**
   * <code>string day = 3;</code>
   */
  java.lang.String getDay();
  /**
   * <code>string day = 3;</code>
   */
  com.google.protobuf.ByteString
      getDayBytes();
}
