// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: tablereservation.proto

package grpc.ca.tablereservation;

public interface CancelReplyOrBuilder extends
    // @@protoc_insertion_point(interface_extends:tablereservation.CancelReply)
    com.google.protobuf.MessageOrBuilder {

  /**
   * <code>string message = 1;</code>
   */
  java.lang.String getMessage();
  /**
   * <code>string message = 1;</code>
   */
  com.google.protobuf.ByteString
      getMessageBytes();
}
