// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: tablereservation.proto

package grpc.ca.tablereservation;

public interface CheckReplyOrBuilder extends
    // @@protoc_insertion_point(interface_extends:tablereservation.CheckReply)
    com.google.protobuf.MessageOrBuilder {

  /**
   * <code>int32 resID = 1;</code>
   */
  int getResID();

  /**
   * <code>int32 noPeople = 2;</code>
   */
  int getNoPeople();

  /**
   * <code>string day = 3;</code>
   */
  java.lang.String getDay();
  /**
   * <code>string day = 3;</code>
   */
  com.google.protobuf.ByteString
      getDayBytes();

  /**
   * <code>string message = 4;</code>
   */
  java.lang.String getMessage();
  /**
   * <code>string message = 4;</code>
   */
  com.google.protobuf.ByteString
      getMessageBytes();
}
