// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: tablereservation.proto

package grpc.ca.tablereservation;

public interface ReserveReplyOrBuilder extends
    // @@protoc_insertion_point(interface_extends:tablereservation.ReserveReply)
    com.google.protobuf.MessageOrBuilder {

  /**
   * <code>int32 resID = 1;</code>
   */
  int getResID();

  /**
   * <code>string message = 2;</code>
   */
  java.lang.String getMessage();
  /**
   * <code>string message = 2;</code>
   */
  com.google.protobuf.ByteString
      getMessageBytes();
}
