// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: tablereservation.proto

package grpc.ca.tablereservation;

public interface ReserveRequestOrBuilder extends
    // @@protoc_insertion_point(interface_extends:tablereservation.ReserveRequest)
    com.google.protobuf.MessageOrBuilder {

  /**
   * <code>int32 nPeople = 1;</code>
   */
  int getNPeople();

  /**
   * <code>string day = 2;</code>
   */
  java.lang.String getDay();
  /**
   * <code>string day = 2;</code>
   */
  com.google.protobuf.ByteString
      getDayBytes();

  /**
   * <code>string time = 3;</code>
   */
  java.lang.String getTime();
  /**
   * <code>string time = 3;</code>
   */
  com.google.protobuf.ByteString
      getTimeBytes();

  /**
   * <code>string name = 4;</code>
   */
  java.lang.String getName();
  /**
   * <code>string name = 4;</code>
   */
  com.google.protobuf.ByteString
      getNameBytes();
}
