// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: tablereservation.proto

package grpc.ca.tablereservation;

public final class TableReservationImpl {
  private TableReservationImpl() {}
  public static void registerAllExtensions(
      com.google.protobuf.ExtensionRegistryLite registry) {
  }

  public static void registerAllExtensions(
      com.google.protobuf.ExtensionRegistry registry) {
    registerAllExtensions(
        (com.google.protobuf.ExtensionRegistryLite) registry);
  }
  static final com.google.protobuf.Descriptors.Descriptor
    internal_static_tablereservation_ReserveRequest_descriptor;
  static final 
    com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
      internal_static_tablereservation_ReserveRequest_fieldAccessorTable;
  static final com.google.protobuf.Descriptors.Descriptor
    internal_static_tablereservation_ReserveReply_descriptor;
  static final 
    com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
      internal_static_tablereservation_ReserveReply_fieldAccessorTable;
  static final com.google.protobuf.Descriptors.Descriptor
    internal_static_tablereservation_CancelRequest_descriptor;
  static final 
    com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
      internal_static_tablereservation_CancelRequest_fieldAccessorTable;
  static final com.google.protobuf.Descriptors.Descriptor
    internal_static_tablereservation_CancelReply_descriptor;
  static final 
    com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
      internal_static_tablereservation_CancelReply_fieldAccessorTable;
  static final com.google.protobuf.Descriptors.Descriptor
    internal_static_tablereservation_CheckRequest_descriptor;
  static final 
    com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
      internal_static_tablereservation_CheckRequest_fieldAccessorTable;
  static final com.google.protobuf.Descriptors.Descriptor
    internal_static_tablereservation_CheckReply_descriptor;
  static final 
    com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
      internal_static_tablereservation_CheckReply_fieldAccessorTable;

  public static com.google.protobuf.Descriptors.FileDescriptor
      getDescriptor() {
    return descriptor;
  }
  private static  com.google.protobuf.Descriptors.FileDescriptor
      descriptor;
  static {
    java.lang.String[] descriptorData = {
      "\n\026tablereservation.proto\022\020tablereservati" +
      "on\"J\n\016ReserveRequest\022\017\n\007nPeople\030\001 \001(\005\022\013\n" +
      "\003day\030\002 \001(\t\022\014\n\004time\030\003 \001(\t\022\014\n\004name\030\004 \001(\t\"." +
      "\n\014ReserveReply\022\r\n\005resID\030\001 \001(\005\022\017\n\007message" +
      "\030\002 \001(\t\"9\n\rCancelRequest\022\r\n\005resID\030\001 \001(\005\022\014" +
      "\n\004name\030\002 \001(\t\022\013\n\003day\030\003 \001(\t\"\036\n\013CancelReply" +
      "\022\017\n\007message\030\001 \001(\t\"+\n\014CheckRequest\022\r\n\005res" +
      "ID\030\001 \001(\005\022\014\n\004name\030\002 \001(\t\"K\n\nCheckReply\022\r\n\005" +
      "resID\030\001 \001(\005\022\020\n\010noPeople\030\002 \001(\005\022\013\n\003day\030\003 \001" +
      "(\t\022\017\n\007message\030\004 \001(\t2\205\002\n\020TableReservation" +
      "\022R\n\014TableReserve\022 .tablereservation.Rese" +
      "rveRequest\032\036.tablereservation.ReserveRep" +
      "ly\"\000\022O\n\013TableCancel\022\037.tablereservation.C" +
      "ancelRequest\032\035.tablereservation.CancelRe" +
      "ply\"\000\022L\n\nTableCheck\022\036.tablereservation.C" +
      "heckRequest\032\034.tablereservation.CheckRepl" +
      "y\"\000B2\n\030grpc.ca.tablereservationB\024TableRe" +
      "servationImplP\001b\006proto3"
    };
    com.google.protobuf.Descriptors.FileDescriptor.InternalDescriptorAssigner assigner =
        new com.google.protobuf.Descriptors.FileDescriptor.    InternalDescriptorAssigner() {
          public com.google.protobuf.ExtensionRegistry assignDescriptors(
              com.google.protobuf.Descriptors.FileDescriptor root) {
            descriptor = root;
            return null;
          }
        };
    com.google.protobuf.Descriptors.FileDescriptor
      .internalBuildGeneratedFileFrom(descriptorData,
        new com.google.protobuf.Descriptors.FileDescriptor[] {
        }, assigner);
    internal_static_tablereservation_ReserveRequest_descriptor =
      getDescriptor().getMessageTypes().get(0);
    internal_static_tablereservation_ReserveRequest_fieldAccessorTable = new
      com.google.protobuf.GeneratedMessageV3.FieldAccessorTable(
        internal_static_tablereservation_ReserveRequest_descriptor,
        new java.lang.String[] { "NPeople", "Day", "Time", "Name", });
    internal_static_tablereservation_ReserveReply_descriptor =
      getDescriptor().getMessageTypes().get(1);
    internal_static_tablereservation_ReserveReply_fieldAccessorTable = new
      com.google.protobuf.GeneratedMessageV3.FieldAccessorTable(
        internal_static_tablereservation_ReserveReply_descriptor,
        new java.lang.String[] { "ResID", "Message", });
    internal_static_tablereservation_CancelRequest_descriptor =
      getDescriptor().getMessageTypes().get(2);
    internal_static_tablereservation_CancelRequest_fieldAccessorTable = new
      com.google.protobuf.GeneratedMessageV3.FieldAccessorTable(
        internal_static_tablereservation_CancelRequest_descriptor,
        new java.lang.String[] { "ResID", "Name", "Day", });
    internal_static_tablereservation_CancelReply_descriptor =
      getDescriptor().getMessageTypes().get(3);
    internal_static_tablereservation_CancelReply_fieldAccessorTable = new
      com.google.protobuf.GeneratedMessageV3.FieldAccessorTable(
        internal_static_tablereservation_CancelReply_descriptor,
        new java.lang.String[] { "Message", });
    internal_static_tablereservation_CheckRequest_descriptor =
      getDescriptor().getMessageTypes().get(4);
    internal_static_tablereservation_CheckRequest_fieldAccessorTable = new
      com.google.protobuf.GeneratedMessageV3.FieldAccessorTable(
        internal_static_tablereservation_CheckRequest_descriptor,
        new java.lang.String[] { "ResID", "Name", });
    internal_static_tablereservation_CheckReply_descriptor =
      getDescriptor().getMessageTypes().get(5);
    internal_static_tablereservation_CheckReply_fieldAccessorTable = new
      com.google.protobuf.GeneratedMessageV3.FieldAccessorTable(
        internal_static_tablereservation_CheckReply_descriptor,
        new java.lang.String[] { "ResID", "NoPeople", "Day", "Message", });
  }

  // @@protoc_insertion_point(outer_class_scope)
}
