// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: review.proto

package grpc.ca.review;

public interface ChatRequestOrBuilder extends
    // @@protoc_insertion_point(interface_extends:review.ChatRequest)
    com.google.protobuf.MessageOrBuilder {

  /**
   * <code>int32 resID = 1;</code>
   */
  int getResID();

  /**
   * <code>string message = 2;</code>
   */
  java.lang.String getMessage();
  /**
   * <code>string message = 2;</code>
   */
  com.google.protobuf.ByteString
      getMessageBytes();
}
