// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: review.proto

package grpc.ca.review;

public interface ChatReplyOrBuilder extends
    // @@protoc_insertion_point(interface_extends:review.ChatReply)
    com.google.protobuf.MessageOrBuilder {

  /**
   * <code>string message = 1;</code>
   */
  java.lang.String getMessage();
  /**
   * <code>string message = 1;</code>
   */
  com.google.protobuf.ByteString
      getMessageBytes();
}
