// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: review.proto

package grpc.ca.review;

public interface EditRequestOrBuilder extends
    // @@protoc_insertion_point(interface_extends:review.EditRequest)
    com.google.protobuf.MessageOrBuilder {

  /**
   * <code>int32 reviewID = 1;</code>
   */
  int getReviewID();

  /**
   * <code>string reviewText = 2;</code>
   */
  java.lang.String getReviewText();
  /**
   * <code>string reviewText = 2;</code>
   */
  com.google.protobuf.ByteString
      getReviewTextBytes();
}
