// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: review.proto

package grpc.ca.review;

public final class ReviewImpl {
  private ReviewImpl() {}
  public static void registerAllExtensions(
      com.google.protobuf.ExtensionRegistryLite registry) {
  }

  public static void registerAllExtensions(
      com.google.protobuf.ExtensionRegistry registry) {
    registerAllExtensions(
        (com.google.protobuf.ExtensionRegistryLite) registry);
  }
  static final com.google.protobuf.Descriptors.Descriptor
    internal_static_review_WriteRequest_descriptor;
  static final 
    com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
      internal_static_review_WriteRequest_fieldAccessorTable;
  static final com.google.protobuf.Descriptors.Descriptor
    internal_static_review_WriteReply_descriptor;
  static final 
    com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
      internal_static_review_WriteReply_fieldAccessorTable;
  static final com.google.protobuf.Descriptors.Descriptor
    internal_static_review_EditRequest_descriptor;
  static final 
    com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
      internal_static_review_EditRequest_fieldAccessorTable;
  static final com.google.protobuf.Descriptors.Descriptor
    internal_static_review_EditReply_descriptor;
  static final 
    com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
      internal_static_review_EditReply_fieldAccessorTable;
  static final com.google.protobuf.Descriptors.Descriptor
    internal_static_review_ChatRequest_descriptor;
  static final 
    com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
      internal_static_review_ChatRequest_fieldAccessorTable;
  static final com.google.protobuf.Descriptors.Descriptor
    internal_static_review_ChatReply_descriptor;
  static final 
    com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
      internal_static_review_ChatReply_fieldAccessorTable;

  public static com.google.protobuf.Descriptors.FileDescriptor
      getDescriptor() {
    return descriptor;
  }
  private static  com.google.protobuf.Descriptors.FileDescriptor
      descriptor;
  static {
    java.lang.String[] descriptorData = {
      "\n\014review.proto\022\006review\"I\n\014WriteRequest\022\r" +
      "\n\005resID\030\001 \001(\005\022\016\n\006rating\030\002 \001(\005\022\014\n\004name\030\003 " +
      "\001(\t\022\014\n\004text\030\004 \001(\t\"/\n\nWriteReply\022\020\n\010revie" +
      "wID\030\001 \001(\005\022\017\n\007message\030\002 \001(\t\"3\n\013EditReques" +
      "t\022\020\n\010reviewID\030\001 \001(\005\022\022\n\nreviewText\030\002 \001(\t\"" +
      "\034\n\tEditReply\022\017\n\007message\030\003 \001(\t\"-\n\013ChatReq" +
      "uest\022\r\n\005resID\030\001 \001(\005\022\017\n\007message\030\002 \001(\t\"\034\n\t" +
      "ChatReply\022\017\n\007message\030\001 \001(\t2\251\001\n\006Review\0225\n" +
      "\005Write\022\024.review.WriteRequest\032\022.review.Wr" +
      "iteReply\"\000(\001\0222\n\004Edit\022\023.review.EditReques" +
      "t\032\021.review.EditReply\"\000(\001\0224\n\004Chat\022\023.revie" +
      "w.ChatRequest\032\021.review.ChatReply\"\000(\0010\001B\036" +
      "\n\016grpc.ca.reviewB\nReviewImplP\001b\006proto3"
    };
    com.google.protobuf.Descriptors.FileDescriptor.InternalDescriptorAssigner assigner =
        new com.google.protobuf.Descriptors.FileDescriptor.    InternalDescriptorAssigner() {
          public com.google.protobuf.ExtensionRegistry assignDescriptors(
              com.google.protobuf.Descriptors.FileDescriptor root) {
            descriptor = root;
            return null;
          }
        };
    com.google.protobuf.Descriptors.FileDescriptor
      .internalBuildGeneratedFileFrom(descriptorData,
        new com.google.protobuf.Descriptors.FileDescriptor[] {
        }, assigner);
    internal_static_review_WriteRequest_descriptor =
      getDescriptor().getMessageTypes().get(0);
    internal_static_review_WriteRequest_fieldAccessorTable = new
      com.google.protobuf.GeneratedMessageV3.FieldAccessorTable(
        internal_static_review_WriteRequest_descriptor,
        new java.lang.String[] { "ResID", "Rating", "Name", "Text", });
    internal_static_review_WriteReply_descriptor =
      getDescriptor().getMessageTypes().get(1);
    internal_static_review_WriteReply_fieldAccessorTable = new
      com.google.protobuf.GeneratedMessageV3.FieldAccessorTable(
        internal_static_review_WriteReply_descriptor,
        new java.lang.String[] { "ReviewID", "Message", });
    internal_static_review_EditRequest_descriptor =
      getDescriptor().getMessageTypes().get(2);
    internal_static_review_EditRequest_fieldAccessorTable = new
      com.google.protobuf.GeneratedMessageV3.FieldAccessorTable(
        internal_static_review_EditRequest_descriptor,
        new java.lang.String[] { "ReviewID", "ReviewText", });
    internal_static_review_EditReply_descriptor =
      getDescriptor().getMessageTypes().get(3);
    internal_static_review_EditReply_fieldAccessorTable = new
      com.google.protobuf.GeneratedMessageV3.FieldAccessorTable(
        internal_static_review_EditReply_descriptor,
        new java.lang.String[] { "Message", });
    internal_static_review_ChatRequest_descriptor =
      getDescriptor().getMessageTypes().get(4);
    internal_static_review_ChatRequest_fieldAccessorTable = new
      com.google.protobuf.GeneratedMessageV3.FieldAccessorTable(
        internal_static_review_ChatRequest_descriptor,
        new java.lang.String[] { "ResID", "Message", });
    internal_static_review_ChatReply_descriptor =
      getDescriptor().getMessageTypes().get(5);
    internal_static_review_ChatReply_fieldAccessorTable = new
      com.google.protobuf.GeneratedMessageV3.FieldAccessorTable(
        internal_static_review_ChatReply_descriptor,
        new java.lang.String[] { "Message", });
  }

  // @@protoc_insertion_point(outer_class_scope)
}
