// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: review.proto

package grpc.ca.review;

public interface WriteReplyOrBuilder extends
    // @@protoc_insertion_point(interface_extends:review.WriteReply)
    com.google.protobuf.MessageOrBuilder {

  /**
   * <code>int32 reviewID = 1;</code>
   */
  int getReviewID();

  /**
   * <code>string message = 2;</code>
   */
  java.lang.String getMessage();
  /**
   * <code>string message = 2;</code>
   */
  com.google.protobuf.ByteString
      getMessageBytes();
}
