// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: review.proto

package grpc.ca.review;

public interface WriteRequestOrBuilder extends
    // @@protoc_insertion_point(interface_extends:review.WriteRequest)
    com.google.protobuf.MessageOrBuilder {

  /**
   * <code>int32 resID = 1;</code>
   */
  int getResID();

  /**
   * <code>int32 rating = 2;</code>
   */
  int getRating();

  /**
   * <code>string name = 3;</code>
   */
  java.lang.String getName();
  /**
   * <code>string name = 3;</code>
   */
  com.google.protobuf.ByteString
      getNameBytes();

  /**
   * <code>string text = 4;</code>
   */
  java.lang.String getText();
  /**
   * <code>string text = 4;</code>
   */
  com.google.protobuf.ByteString
      getTextBytes();
}
