// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: preorder.proto

package grpc.ca.preorder;

public interface MenuRequestOrBuilder extends
    // @@protoc_insertion_point(interface_extends:preorder.MenuRequest)
    com.google.protobuf.MessageOrBuilder {

  /**
   * <code>string request = 1;</code>
   */
  java.lang.String getRequest();
  /**
   * <code>string request = 1;</code>
   */
  com.google.protobuf.ByteString
      getRequestBytes();
}
