// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: preorder.proto

package grpc.ca.preorder;

/**
 * Protobuf type {@code preorder.MenuReply}
 */
public  final class MenuReply extends
    com.google.protobuf.GeneratedMessageV3 implements
    // @@protoc_insertion_point(message_implements:preorder.MenuReply)
    MenuReplyOrBuilder {
private static final long serialVersionUID = 0L;
  // Use MenuReply.newBuilder() to construct.
  private MenuReply(com.google.protobuf.GeneratedMessageV3.Builder<?> builder) {
    super(builder);
  }
  private MenuReply() {
    hamburger_ = "";
    cheeseburger_ = "";
    coke_ = "";
    fanta_ = "";
    resID_ = 0;
  }

  @java.lang.Override
  public final com.google.protobuf.UnknownFieldSet
  getUnknownFields() {
    return this.unknownFields;
  }
  private MenuReply(
      com.google.protobuf.CodedInputStream input,
      com.google.protobuf.ExtensionRegistryLite extensionRegistry)
      throws com.google.protobuf.InvalidProtocolBufferException {
    this();
    if (extensionRegistry == null) {
      throw new java.lang.NullPointerException();
    }
    int mutable_bitField0_ = 0;
    com.google.protobuf.UnknownFieldSet.Builder unknownFields =
        com.google.protobuf.UnknownFieldSet.newBuilder();
    try {
      boolean done = false;
      while (!done) {
        int tag = input.readTag();
        switch (tag) {
          case 0:
            done = true;
            break;
          case 10: {
            java.lang.String s = input.readStringRequireUtf8();

            hamburger_ = s;
            break;
          }
          case 18: {
            java.lang.String s = input.readStringRequireUtf8();

            cheeseburger_ = s;
            break;
          }
          case 26: {
            java.lang.String s = input.readStringRequireUtf8();

            coke_ = s;
            break;
          }
          case 34: {
            java.lang.String s = input.readStringRequireUtf8();

            fanta_ = s;
            break;
          }
          case 40: {

            resID_ = input.readInt32();
            break;
          }
          default: {
            if (!parseUnknownFieldProto3(
                input, unknownFields, extensionRegistry, tag)) {
              done = true;
            }
            break;
          }
        }
      }
    } catch (com.google.protobuf.InvalidProtocolBufferException e) {
      throw e.setUnfinishedMessage(this);
    } catch (java.io.IOException e) {
      throw new com.google.protobuf.InvalidProtocolBufferException(
          e).setUnfinishedMessage(this);
    } finally {
      this.unknownFields = unknownFields.build();
      makeExtensionsImmutable();
    }
  }
  public static final com.google.protobuf.Descriptors.Descriptor
      getDescriptor() {
    return grpc.ca.preorder.PreOrderImpl.internal_static_preorder_MenuReply_descriptor;
  }

  @java.lang.Override
  protected com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
      internalGetFieldAccessorTable() {
    return grpc.ca.preorder.PreOrderImpl.internal_static_preorder_MenuReply_fieldAccessorTable
        .ensureFieldAccessorsInitialized(
            grpc.ca.preorder.MenuReply.class, grpc.ca.preorder.MenuReply.Builder.class);
  }

  public static final int HAMBURGER_FIELD_NUMBER = 1;
  private volatile java.lang.Object hamburger_;
  /**
   * <code>string hamburger = 1;</code>
   */
  public java.lang.String getHamburger() {
    java.lang.Object ref = hamburger_;
    if (ref instanceof java.lang.String) {
      return (java.lang.String) ref;
    } else {
      com.google.protobuf.ByteString bs = 
          (com.google.protobuf.ByteString) ref;
      java.lang.String s = bs.toStringUtf8();
      hamburger_ = s;
      return s;
    }
  }
  /**
   * <code>string hamburger = 1;</code>
   */
  public com.google.protobuf.ByteString
      getHamburgerBytes() {
    java.lang.Object ref = hamburger_;
    if (ref instanceof java.lang.String) {
      com.google.protobuf.ByteString b = 
          com.google.protobuf.ByteString.copyFromUtf8(
              (java.lang.String) ref);
      hamburger_ = b;
      return b;
    } else {
      return (com.google.protobuf.ByteString) ref;
    }
  }

  public static final int CHEESEBURGER_FIELD_NUMBER = 2;
  private volatile java.lang.Object cheeseburger_;
  /**
   * <code>string cheeseburger = 2;</code>
   */
  public java.lang.String getCheeseburger() {
    java.lang.Object ref = cheeseburger_;
    if (ref instanceof java.lang.String) {
      return (java.lang.String) ref;
    } else {
      com.google.protobuf.ByteString bs = 
          (com.google.protobuf.ByteString) ref;
      java.lang.String s = bs.toStringUtf8();
      cheeseburger_ = s;
      return s;
    }
  }
  /**
   * <code>string cheeseburger = 2;</code>
   */
  public com.google.protobuf.ByteString
      getCheeseburgerBytes() {
    java.lang.Object ref = cheeseburger_;
    if (ref instanceof java.lang.String) {
      com.google.protobuf.ByteString b = 
          com.google.protobuf.ByteString.copyFromUtf8(
              (java.lang.String) ref);
      cheeseburger_ = b;
      return b;
    } else {
      return (com.google.protobuf.ByteString) ref;
    }
  }

  public static final int COKE_FIELD_NUMBER = 3;
  private volatile java.lang.Object coke_;
  /**
   * <code>string coke = 3;</code>
   */
  public java.lang.String getCoke() {
    java.lang.Object ref = coke_;
    if (ref instanceof java.lang.String) {
      return (java.lang.String) ref;
    } else {
      com.google.protobuf.ByteString bs = 
          (com.google.protobuf.ByteString) ref;
      java.lang.String s = bs.toStringUtf8();
      coke_ = s;
      return s;
    }
  }
  /**
   * <code>string coke = 3;</code>
   */
  public com.google.protobuf.ByteString
      getCokeBytes() {
    java.lang.Object ref = coke_;
    if (ref instanceof java.lang.String) {
      com.google.protobuf.ByteString b = 
          com.google.protobuf.ByteString.copyFromUtf8(
              (java.lang.String) ref);
      coke_ = b;
      return b;
    } else {
      return (com.google.protobuf.ByteString) ref;
    }
  }

  public static final int FANTA_FIELD_NUMBER = 4;
  private volatile java.lang.Object fanta_;
  /**
   * <code>string fanta = 4;</code>
   */
  public java.lang.String getFanta() {
    java.lang.Object ref = fanta_;
    if (ref instanceof java.lang.String) {
      return (java.lang.String) ref;
    } else {
      com.google.protobuf.ByteString bs = 
          (com.google.protobuf.ByteString) ref;
      java.lang.String s = bs.toStringUtf8();
      fanta_ = s;
      return s;
    }
  }
  /**
   * <code>string fanta = 4;</code>
   */
  public com.google.protobuf.ByteString
      getFantaBytes() {
    java.lang.Object ref = fanta_;
    if (ref instanceof java.lang.String) {
      com.google.protobuf.ByteString b = 
          com.google.protobuf.ByteString.copyFromUtf8(
              (java.lang.String) ref);
      fanta_ = b;
      return b;
    } else {
      return (com.google.protobuf.ByteString) ref;
    }
  }

  public static final int RESID_FIELD_NUMBER = 5;
  private int resID_;
  /**
   * <code>int32 resID = 5;</code>
   */
  public int getResID() {
    return resID_;
  }

  private byte memoizedIsInitialized = -1;
  @java.lang.Override
  public final boolean isInitialized() {
    byte isInitialized = memoizedIsInitialized;
    if (isInitialized == 1) return true;
    if (isInitialized == 0) return false;

    memoizedIsInitialized = 1;
    return true;
  }

  @java.lang.Override
  public void writeTo(com.google.protobuf.CodedOutputStream output)
                      throws java.io.IOException {
    if (!getHamburgerBytes().isEmpty()) {
      com.google.protobuf.GeneratedMessageV3.writeString(output, 1, hamburger_);
    }
    if (!getCheeseburgerBytes().isEmpty()) {
      com.google.protobuf.GeneratedMessageV3.writeString(output, 2, cheeseburger_);
    }
    if (!getCokeBytes().isEmpty()) {
      com.google.protobuf.GeneratedMessageV3.writeString(output, 3, coke_);
    }
    if (!getFantaBytes().isEmpty()) {
      com.google.protobuf.GeneratedMessageV3.writeString(output, 4, fanta_);
    }
    if (resID_ != 0) {
      output.writeInt32(5, resID_);
    }
    unknownFields.writeTo(output);
  }

  @java.lang.Override
  public int getSerializedSize() {
    int size = memoizedSize;
    if (size != -1) return size;

    size = 0;
    if (!getHamburgerBytes().isEmpty()) {
      size += com.google.protobuf.GeneratedMessageV3.computeStringSize(1, hamburger_);
    }
    if (!getCheeseburgerBytes().isEmpty()) {
      size += com.google.protobuf.GeneratedMessageV3.computeStringSize(2, cheeseburger_);
    }
    if (!getCokeBytes().isEmpty()) {
      size += com.google.protobuf.GeneratedMessageV3.computeStringSize(3, coke_);
    }
    if (!getFantaBytes().isEmpty()) {
      size += com.google.protobuf.GeneratedMessageV3.computeStringSize(4, fanta_);
    }
    if (resID_ != 0) {
      size += com.google.protobuf.CodedOutputStream
        .computeInt32Size(5, resID_);
    }
    size += unknownFields.getSerializedSize();
    memoizedSize = size;
    return size;
  }

  @java.lang.Override
  public boolean equals(final java.lang.Object obj) {
    if (obj == this) {
     return true;
    }
    if (!(obj instanceof grpc.ca.preorder.MenuReply)) {
      return super.equals(obj);
    }
    grpc.ca.preorder.MenuReply other = (grpc.ca.preorder.MenuReply) obj;

    boolean result = true;
    result = result && getHamburger()
        .equals(other.getHamburger());
    result = result && getCheeseburger()
        .equals(other.getCheeseburger());
    result = result && getCoke()
        .equals(other.getCoke());
    result = result && getFanta()
        .equals(other.getFanta());
    result = result && (getResID()
        == other.getResID());
    result = result && unknownFields.equals(other.unknownFields);
    return result;
  }

  @java.lang.Override
  public int hashCode() {
    if (memoizedHashCode != 0) {
      return memoizedHashCode;
    }
    int hash = 41;
    hash = (19 * hash) + getDescriptor().hashCode();
    hash = (37 * hash) + HAMBURGER_FIELD_NUMBER;
    hash = (53 * hash) + getHamburger().hashCode();
    hash = (37 * hash) + CHEESEBURGER_FIELD_NUMBER;
    hash = (53 * hash) + getCheeseburger().hashCode();
    hash = (37 * hash) + COKE_FIELD_NUMBER;
    hash = (53 * hash) + getCoke().hashCode();
    hash = (37 * hash) + FANTA_FIELD_NUMBER;
    hash = (53 * hash) + getFanta().hashCode();
    hash = (37 * hash) + RESID_FIELD_NUMBER;
    hash = (53 * hash) + getResID();
    hash = (29 * hash) + unknownFields.hashCode();
    memoizedHashCode = hash;
    return hash;
  }

  public static grpc.ca.preorder.MenuReply parseFrom(
      java.nio.ByteBuffer data)
      throws com.google.protobuf.InvalidProtocolBufferException {
    return PARSER.parseFrom(data);
  }
  public static grpc.ca.preorder.MenuReply parseFrom(
      java.nio.ByteBuffer data,
      com.google.protobuf.ExtensionRegistryLite extensionRegistry)
      throws com.google.protobuf.InvalidProtocolBufferException {
    return PARSER.parseFrom(data, extensionRegistry);
  }
  public static grpc.ca.preorder.MenuReply parseFrom(
      com.google.protobuf.ByteString data)
      throws com.google.protobuf.InvalidProtocolBufferException {
    return PARSER.parseFrom(data);
  }
  public static grpc.ca.preorder.MenuReply parseFrom(
      com.google.protobuf.ByteString data,
      com.google.protobuf.ExtensionRegistryLite extensionRegistry)
      throws com.google.protobuf.InvalidProtocolBufferException {
    return PARSER.parseFrom(data, extensionRegistry);
  }
  public static grpc.ca.preorder.MenuReply parseFrom(byte[] data)
      throws com.google.protobuf.InvalidProtocolBufferException {
    return PARSER.parseFrom(data);
  }
  public static grpc.ca.preorder.MenuReply parseFrom(
      byte[] data,
      com.google.protobuf.ExtensionRegistryLite extensionRegistry)
      throws com.google.protobuf.InvalidProtocolBufferException {
    return PARSER.parseFrom(data, extensionRegistry);
  }
  public static grpc.ca.preorder.MenuReply parseFrom(java.io.InputStream input)
      throws java.io.IOException {
    return com.google.protobuf.GeneratedMessageV3
        .parseWithIOException(PARSER, input);
  }
  public static grpc.ca.preorder.MenuReply parseFrom(
      java.io.InputStream input,
      com.google.protobuf.ExtensionRegistryLite extensionRegistry)
      throws java.io.IOException {
    return com.google.protobuf.GeneratedMessageV3
        .parseWithIOException(PARSER, input, extensionRegistry);
  }
  public static grpc.ca.preorder.MenuReply parseDelimitedFrom(java.io.InputStream input)
      throws java.io.IOException {
    return com.google.protobuf.GeneratedMessageV3
        .parseDelimitedWithIOException(PARSER, input);
  }
  public static grpc.ca.preorder.MenuReply parseDelimitedFrom(
      java.io.InputStream input,
      com.google.protobuf.ExtensionRegistryLite extensionRegistry)
      throws java.io.IOException {
    return com.google.protobuf.GeneratedMessageV3
        .parseDelimitedWithIOException(PARSER, input, extensionRegistry);
  }
  public static grpc.ca.preorder.MenuReply parseFrom(
      com.google.protobuf.CodedInputStream input)
      throws java.io.IOException {
    return com.google.protobuf.GeneratedMessageV3
        .parseWithIOException(PARSER, input);
  }
  public static grpc.ca.preorder.MenuReply parseFrom(
      com.google.protobuf.CodedInputStream input,
      com.google.protobuf.ExtensionRegistryLite extensionRegistry)
      throws java.io.IOException {
    return com.google.protobuf.GeneratedMessageV3
        .parseWithIOException(PARSER, input, extensionRegistry);
  }

  @java.lang.Override
  public Builder newBuilderForType() { return newBuilder(); }
  public static Builder newBuilder() {
    return DEFAULT_INSTANCE.toBuilder();
  }
  public static Builder newBuilder(grpc.ca.preorder.MenuReply prototype) {
    return DEFAULT_INSTANCE.toBuilder().mergeFrom(prototype);
  }
  @java.lang.Override
  public Builder toBuilder() {
    return this == DEFAULT_INSTANCE
        ? new Builder() : new Builder().mergeFrom(this);
  }

  @java.lang.Override
  protected Builder newBuilderForType(
      com.google.protobuf.GeneratedMessageV3.BuilderParent parent) {
    Builder builder = new Builder(parent);
    return builder;
  }
  /**
   * Protobuf type {@code preorder.MenuReply}
   */
  public static final class Builder extends
      com.google.protobuf.GeneratedMessageV3.Builder<Builder> implements
      // @@protoc_insertion_point(builder_implements:preorder.MenuReply)
      grpc.ca.preorder.MenuReplyOrBuilder {
    public static final com.google.protobuf.Descriptors.Descriptor
        getDescriptor() {
      return grpc.ca.preorder.PreOrderImpl.internal_static_preorder_MenuReply_descriptor;
    }

    @java.lang.Override
    protected com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
        internalGetFieldAccessorTable() {
      return grpc.ca.preorder.PreOrderImpl.internal_static_preorder_MenuReply_fieldAccessorTable
          .ensureFieldAccessorsInitialized(
              grpc.ca.preorder.MenuReply.class, grpc.ca.preorder.MenuReply.Builder.class);
    }

    // Construct using grpc.ca.preorder.MenuReply.newBuilder()
    private Builder() {
      maybeForceBuilderInitialization();
    }

    private Builder(
        com.google.protobuf.GeneratedMessageV3.BuilderParent parent) {
      super(parent);
      maybeForceBuilderInitialization();
    }
    private void maybeForceBuilderInitialization() {
      if (com.google.protobuf.GeneratedMessageV3
              .alwaysUseFieldBuilders) {
      }
    }
    @java.lang.Override
    public Builder clear() {
      super.clear();
      hamburger_ = "";

      cheeseburger_ = "";

      coke_ = "";

      fanta_ = "";

      resID_ = 0;

      return this;
    }

    @java.lang.Override
    public com.google.protobuf.Descriptors.Descriptor
        getDescriptorForType() {
      return grpc.ca.preorder.PreOrderImpl.internal_static_preorder_MenuReply_descriptor;
    }

    @java.lang.Override
    public grpc.ca.preorder.MenuReply getDefaultInstanceForType() {
      return grpc.ca.preorder.MenuReply.getDefaultInstance();
    }

    @java.lang.Override
    public grpc.ca.preorder.MenuReply build() {
      grpc.ca.preorder.MenuReply result = buildPartial();
      if (!result.isInitialized()) {
        throw newUninitializedMessageException(result);
      }
      return result;
    }

    @java.lang.Override
    public grpc.ca.preorder.MenuReply buildPartial() {
      grpc.ca.preorder.MenuReply result = new grpc.ca.preorder.MenuReply(this);
      result.hamburger_ = hamburger_;
      result.cheeseburger_ = cheeseburger_;
      result.coke_ = coke_;
      result.fanta_ = fanta_;
      result.resID_ = resID_;
      onBuilt();
      return result;
    }

    @java.lang.Override
    public Builder clone() {
      return (Builder) super.clone();
    }
    @java.lang.Override
    public Builder setField(
        com.google.protobuf.Descriptors.FieldDescriptor field,
        java.lang.Object value) {
      return (Builder) super.setField(field, value);
    }
    @java.lang.Override
    public Builder clearField(
        com.google.protobuf.Descriptors.FieldDescriptor field) {
      return (Builder) super.clearField(field);
    }
    @java.lang.Override
    public Builder clearOneof(
        com.google.protobuf.Descriptors.OneofDescriptor oneof) {
      return (Builder) super.clearOneof(oneof);
    }
    @java.lang.Override
    public Builder setRepeatedField(
        com.google.protobuf.Descriptors.FieldDescriptor field,
        int index, java.lang.Object value) {
      return (Builder) super.setRepeatedField(field, index, value);
    }
    @java.lang.Override
    public Builder addRepeatedField(
        com.google.protobuf.Descriptors.FieldDescriptor field,
        java.lang.Object value) {
      return (Builder) super.addRepeatedField(field, value);
    }
    @java.lang.Override
    public Builder mergeFrom(com.google.protobuf.Message other) {
      if (other instanceof grpc.ca.preorder.MenuReply) {
        return mergeFrom((grpc.ca.preorder.MenuReply)other);
      } else {
        super.mergeFrom(other);
        return this;
      }
    }

    public Builder mergeFrom(grpc.ca.preorder.MenuReply other) {
      if (other == grpc.ca.preorder.MenuReply.getDefaultInstance()) return this;
      if (!other.getHamburger().isEmpty()) {
        hamburger_ = other.hamburger_;
        onChanged();
      }
      if (!other.getCheeseburger().isEmpty()) {
        cheeseburger_ = other.cheeseburger_;
        onChanged();
      }
      if (!other.getCoke().isEmpty()) {
        coke_ = other.coke_;
        onChanged();
      }
      if (!other.getFanta().isEmpty()) {
        fanta_ = other.fanta_;
        onChanged();
      }
      if (other.getResID() != 0) {
        setResID(other.getResID());
      }
      this.mergeUnknownFields(other.unknownFields);
      onChanged();
      return this;
    }

    @java.lang.Override
    public final boolean isInitialized() {
      return true;
    }

    @java.lang.Override
    public Builder mergeFrom(
        com.google.protobuf.CodedInputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      grpc.ca.preorder.MenuReply parsedMessage = null;
      try {
        parsedMessage = PARSER.parsePartialFrom(input, extensionRegistry);
      } catch (com.google.protobuf.InvalidProtocolBufferException e) {
        parsedMessage = (grpc.ca.preorder.MenuReply) e.getUnfinishedMessage();
        throw e.unwrapIOException();
      } finally {
        if (parsedMessage != null) {
          mergeFrom(parsedMessage);
        }
      }
      return this;
    }

    private java.lang.Object hamburger_ = "";
    /**
     * <code>string hamburger = 1;</code>
     */
    public java.lang.String getHamburger() {
      java.lang.Object ref = hamburger_;
      if (!(ref instanceof java.lang.String)) {
        com.google.protobuf.ByteString bs =
            (com.google.protobuf.ByteString) ref;
        java.lang.String s = bs.toStringUtf8();
        hamburger_ = s;
        return s;
      } else {
        return (java.lang.String) ref;
      }
    }
    /**
     * <code>string hamburger = 1;</code>
     */
    public com.google.protobuf.ByteString
        getHamburgerBytes() {
      java.lang.Object ref = hamburger_;
      if (ref instanceof String) {
        com.google.protobuf.ByteString b = 
            com.google.protobuf.ByteString.copyFromUtf8(
                (java.lang.String) ref);
        hamburger_ = b;
        return b;
      } else {
        return (com.google.protobuf.ByteString) ref;
      }
    }
    /**
     * <code>string hamburger = 1;</code>
     */
    public Builder setHamburger(
        java.lang.String value) {
      if (value == null) {
    throw new NullPointerException();
  }
  
      hamburger_ = value;
      onChanged();
      return this;
    }
    /**
     * <code>string hamburger = 1;</code>
     */
    public Builder clearHamburger() {
      
      hamburger_ = getDefaultInstance().getHamburger();
      onChanged();
      return this;
    }
    /**
     * <code>string hamburger = 1;</code>
     */
    public Builder setHamburgerBytes(
        com.google.protobuf.ByteString value) {
      if (value == null) {
    throw new NullPointerException();
  }
  checkByteStringIsUtf8(value);
      
      hamburger_ = value;
      onChanged();
      return this;
    }

    private java.lang.Object cheeseburger_ = "";
    /**
     * <code>string cheeseburger = 2;</code>
     */
    public java.lang.String getCheeseburger() {
      java.lang.Object ref = cheeseburger_;
      if (!(ref instanceof java.lang.String)) {
        com.google.protobuf.ByteString bs =
            (com.google.protobuf.ByteString) ref;
        java.lang.String s = bs.toStringUtf8();
        cheeseburger_ = s;
        return s;
      } else {
        return (java.lang.String) ref;
      }
    }
    /**
     * <code>string cheeseburger = 2;</code>
     */
    public com.google.protobuf.ByteString
        getCheeseburgerBytes() {
      java.lang.Object ref = cheeseburger_;
      if (ref instanceof String) {
        com.google.protobuf.ByteString b = 
            com.google.protobuf.ByteString.copyFromUtf8(
                (java.lang.String) ref);
        cheeseburger_ = b;
        return b;
      } else {
        return (com.google.protobuf.ByteString) ref;
      }
    }
    /**
     * <code>string cheeseburger = 2;</code>
     */
    public Builder setCheeseburger(
        java.lang.String value) {
      if (value == null) {
    throw new NullPointerException();
  }
  
      cheeseburger_ = value;
      onChanged();
      return this;
    }
    /**
     * <code>string cheeseburger = 2;</code>
     */
    public Builder clearCheeseburger() {
      
      cheeseburger_ = getDefaultInstance().getCheeseburger();
      onChanged();
      return this;
    }
    /**
     * <code>string cheeseburger = 2;</code>
     */
    public Builder setCheeseburgerBytes(
        com.google.protobuf.ByteString value) {
      if (value == null) {
    throw new NullPointerException();
  }
  checkByteStringIsUtf8(value);
      
      cheeseburger_ = value;
      onChanged();
      return this;
    }

    private java.lang.Object coke_ = "";
    /**
     * <code>string coke = 3;</code>
     */
    public java.lang.String getCoke() {
      java.lang.Object ref = coke_;
      if (!(ref instanceof java.lang.String)) {
        com.google.protobuf.ByteString bs =
            (com.google.protobuf.ByteString) ref;
        java.lang.String s = bs.toStringUtf8();
        coke_ = s;
        return s;
      } else {
        return (java.lang.String) ref;
      }
    }
    /**
     * <code>string coke = 3;</code>
     */
    public com.google.protobuf.ByteString
        getCokeBytes() {
      java.lang.Object ref = coke_;
      if (ref instanceof String) {
        com.google.protobuf.ByteString b = 
            com.google.protobuf.ByteString.copyFromUtf8(
                (java.lang.String) ref);
        coke_ = b;
        return b;
      } else {
        return (com.google.protobuf.ByteString) ref;
      }
    }
    /**
     * <code>string coke = 3;</code>
     */
    public Builder setCoke(
        java.lang.String value) {
      if (value == null) {
    throw new NullPointerException();
  }
  
      coke_ = value;
      onChanged();
      return this;
    }
    /**
     * <code>string coke = 3;</code>
     */
    public Builder clearCoke() {
      
      coke_ = getDefaultInstance().getCoke();
      onChanged();
      return this;
    }
    /**
     * <code>string coke = 3;</code>
     */
    public Builder setCokeBytes(
        com.google.protobuf.ByteString value) {
      if (value == null) {
    throw new NullPointerException();
  }
  checkByteStringIsUtf8(value);
      
      coke_ = value;
      onChanged();
      return this;
    }

    private java.lang.Object fanta_ = "";
    /**
     * <code>string fanta = 4;</code>
     */
    public java.lang.String getFanta() {
      java.lang.Object ref = fanta_;
      if (!(ref instanceof java.lang.String)) {
        com.google.protobuf.ByteString bs =
            (com.google.protobuf.ByteString) ref;
        java.lang.String s = bs.toStringUtf8();
        fanta_ = s;
        return s;
      } else {
        return (java.lang.String) ref;
      }
    }
    /**
     * <code>string fanta = 4;</code>
     */
    public com.google.protobuf.ByteString
        getFantaBytes() {
      java.lang.Object ref = fanta_;
      if (ref instanceof String) {
        com.google.protobuf.ByteString b = 
            com.google.protobuf.ByteString.copyFromUtf8(
                (java.lang.String) ref);
        fanta_ = b;
        return b;
      } else {
        return (com.google.protobuf.ByteString) ref;
      }
    }
    /**
     * <code>string fanta = 4;</code>
     */
    public Builder setFanta(
        java.lang.String value) {
      if (value == null) {
    throw new NullPointerException();
  }
  
      fanta_ = value;
      onChanged();
      return this;
    }
    /**
     * <code>string fanta = 4;</code>
     */
    public Builder clearFanta() {
      
      fanta_ = getDefaultInstance().getFanta();
      onChanged();
      return this;
    }
    /**
     * <code>string fanta = 4;</code>
     */
    public Builder setFantaBytes(
        com.google.protobuf.ByteString value) {
      if (value == null) {
    throw new NullPointerException();
  }
  checkByteStringIsUtf8(value);
      
      fanta_ = value;
      onChanged();
      return this;
    }

    private int resID_ ;
    /**
     * <code>int32 resID = 5;</code>
     */
    public int getResID() {
      return resID_;
    }
    /**
     * <code>int32 resID = 5;</code>
     */
    public Builder setResID(int value) {
      
      resID_ = value;
      onChanged();
      return this;
    }
    /**
     * <code>int32 resID = 5;</code>
     */
    public Builder clearResID() {
      
      resID_ = 0;
      onChanged();
      return this;
    }
    @java.lang.Override
    public final Builder setUnknownFields(
        final com.google.protobuf.UnknownFieldSet unknownFields) {
      return super.setUnknownFieldsProto3(unknownFields);
    }

    @java.lang.Override
    public final Builder mergeUnknownFields(
        final com.google.protobuf.UnknownFieldSet unknownFields) {
      return super.mergeUnknownFields(unknownFields);
    }


    // @@protoc_insertion_point(builder_scope:preorder.MenuReply)
  }

  // @@protoc_insertion_point(class_scope:preorder.MenuReply)
  private static final grpc.ca.preorder.MenuReply DEFAULT_INSTANCE;
  static {
    DEFAULT_INSTANCE = new grpc.ca.preorder.MenuReply();
  }

  public static grpc.ca.preorder.MenuReply getDefaultInstance() {
    return DEFAULT_INSTANCE;
  }

  private static final com.google.protobuf.Parser<MenuReply>
      PARSER = new com.google.protobuf.AbstractParser<MenuReply>() {
    @java.lang.Override
    public MenuReply parsePartialFrom(
        com.google.protobuf.CodedInputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return new MenuReply(input, extensionRegistry);
    }
  };

  public static com.google.protobuf.Parser<MenuReply> parser() {
    return PARSER;
  }

  @java.lang.Override
  public com.google.protobuf.Parser<MenuReply> getParserForType() {
    return PARSER;
  }

  @java.lang.Override
  public grpc.ca.preorder.MenuReply getDefaultInstanceForType() {
    return DEFAULT_INSTANCE;
  }

}

