// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: preorder.proto

package grpc.ca.preorder;

public interface MenuReplyOrBuilder extends
    // @@protoc_insertion_point(interface_extends:preorder.MenuReply)
    com.google.protobuf.MessageOrBuilder {

  /**
   * <code>string hamburger = 1;</code>
   */
  java.lang.String getHamburger();
  /**
   * <code>string hamburger = 1;</code>
   */
  com.google.protobuf.ByteString
      getHamburgerBytes();

  /**
   * <code>string cheeseburger = 2;</code>
   */
  java.lang.String getCheeseburger();
  /**
   * <code>string cheeseburger = 2;</code>
   */
  com.google.protobuf.ByteString
      getCheeseburgerBytes();

  /**
   * <code>string coke = 3;</code>
   */
  java.lang.String getCoke();
  /**
   * <code>string coke = 3;</code>
   */
  com.google.protobuf.ByteString
      getCokeBytes();

  /**
   * <code>string fanta = 4;</code>
   */
  java.lang.String getFanta();
  /**
   * <code>string fanta = 4;</code>
   */
  com.google.protobuf.ByteString
      getFantaBytes();

  /**
   * <code>int32 resID = 5;</code>
   */
  int getResID();
}
