// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: preorder.proto

package grpc.ca.preorder;

public interface OrderReplyOrBuilder extends
    // @@protoc_insertion_point(interface_extends:preorder.OrderReply)
    com.google.protobuf.MessageOrBuilder {

  /**
   * <code>int32 orderNo = 1;</code>
   */
  int getOrderNo();

  /**
   * <code>int32 totalPrice = 2;</code>
   */
  int getTotalPrice();

  /**
   * <code>string message = 3;</code>
   */
  java.lang.String getMessage();
  /**
   * <code>string message = 3;</code>
   */
  com.google.protobuf.ByteString
      getMessageBytes();
}
