// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: preorder.proto

package grpc.ca.preorder;

public interface OrderRequestOrBuilder extends
    // @@protoc_insertion_point(interface_extends:preorder.OrderRequest)
    com.google.protobuf.MessageOrBuilder {

  /**
   * <code>string food = 1;</code>
   */
  java.lang.String getFood();
  /**
   * <code>string food = 1;</code>
   */
  com.google.protobuf.ByteString
      getFoodBytes();

  /**
   * <code>string drink = 2;</code>
   */
  java.lang.String getDrink();
  /**
   * <code>string drink = 2;</code>
   */
  com.google.protobuf.ByteString
      getDrinkBytes();

  /**
   * <code>int32 qty = 3;</code>
   */
  int getQty();
}
