// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: preorder.proto

package grpc.ca.preorder;

public final class PreOrderImpl {
  private PreOrderImpl() {}
  public static void registerAllExtensions(
      com.google.protobuf.ExtensionRegistryLite registry) {
  }

  public static void registerAllExtensions(
      com.google.protobuf.ExtensionRegistry registry) {
    registerAllExtensions(
        (com.google.protobuf.ExtensionRegistryLite) registry);
  }
  static final com.google.protobuf.Descriptors.Descriptor
    internal_static_preorder_MenuRequest_descriptor;
  static final 
    com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
      internal_static_preorder_MenuRequest_fieldAccessorTable;
  static final com.google.protobuf.Descriptors.Descriptor
    internal_static_preorder_MenuReply_descriptor;
  static final 
    com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
      internal_static_preorder_MenuReply_fieldAccessorTable;
  static final com.google.protobuf.Descriptors.Descriptor
    internal_static_preorder_OrderRequest_descriptor;
  static final 
    com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
      internal_static_preorder_OrderRequest_fieldAccessorTable;
  static final com.google.protobuf.Descriptors.Descriptor
    internal_static_preorder_OrderReply_descriptor;
  static final 
    com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
      internal_static_preorder_OrderReply_fieldAccessorTable;
  static final com.google.protobuf.Descriptors.Descriptor
    internal_static_preorder_StatusRequest_descriptor;
  static final 
    com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
      internal_static_preorder_StatusRequest_fieldAccessorTable;
  static final com.google.protobuf.Descriptors.Descriptor
    internal_static_preorder_StatusReply_descriptor;
  static final 
    com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
      internal_static_preorder_StatusReply_fieldAccessorTable;

  public static com.google.protobuf.Descriptors.FileDescriptor
      getDescriptor() {
    return descriptor;
  }
  private static  com.google.protobuf.Descriptors.FileDescriptor
      descriptor;
  static {
    java.lang.String[] descriptorData = {
      "\n\016preorder.proto\022\010preorder\"\036\n\013MenuReques" +
      "t\022\017\n\007request\030\001 \001(\t\"`\n\tMenuReply\022\021\n\thambu" +
      "rger\030\001 \001(\t\022\024\n\014cheeseburger\030\002 \001(\t\022\014\n\004coke" +
      "\030\003 \001(\t\022\r\n\005fanta\030\004 \001(\t\022\r\n\005resID\030\005 \001(\005\"8\n\014" +
      "OrderRequest\022\014\n\004food\030\001 \001(\t\022\r\n\005drink\030\002 \001(" +
      "\t\022\013\n\003qty\030\003 \001(\005\"B\n\nOrderReply\022\017\n\007orderNo\030" +
      "\001 \001(\005\022\022\n\ntotalPrice\030\002 \001(\005\022\017\n\007message\030\003 \001" +
      "(\t\" \n\rStatusRequest\022\017\n\007orderNo\030\001 \001(\005\"\035\n\013" +
      "StatusReply\022\016\n\006Status\030\001 \001(\t2\271\001\n\010PreOrder" +
      "\0224\n\004Menu\022\025.preorder.MenuRequest\032\023.preord" +
      "er.MenuReply\"\000\0229\n\005Order\022\026.preorder.Order" +
      "Request\032\024.preorder.OrderReply\"\0000\001\022<\n\006Sta" +
      "tus\022\027.preorder.StatusRequest\032\025.preorder." +
      "StatusReply\"\0000\001B\"\n\020grpc.ca.preorderB\014Pre" +
      "OrderImplP\001b\006proto3"
    };
    com.google.protobuf.Descriptors.FileDescriptor.InternalDescriptorAssigner assigner =
        new com.google.protobuf.Descriptors.FileDescriptor.    InternalDescriptorAssigner() {
          public com.google.protobuf.ExtensionRegistry assignDescriptors(
              com.google.protobuf.Descriptors.FileDescriptor root) {
            descriptor = root;
            return null;
          }
        };
    com.google.protobuf.Descriptors.FileDescriptor
      .internalBuildGeneratedFileFrom(descriptorData,
        new com.google.protobuf.Descriptors.FileDescriptor[] {
        }, assigner);
    internal_static_preorder_MenuRequest_descriptor =
      getDescriptor().getMessageTypes().get(0);
    internal_static_preorder_MenuRequest_fieldAccessorTable = new
      com.google.protobuf.GeneratedMessageV3.FieldAccessorTable(
        internal_static_preorder_MenuRequest_descriptor,
        new java.lang.String[] { "Request", });
    internal_static_preorder_MenuReply_descriptor =
      getDescriptor().getMessageTypes().get(1);
    internal_static_preorder_MenuReply_fieldAccessorTable = new
      com.google.protobuf.GeneratedMessageV3.FieldAccessorTable(
        internal_static_preorder_MenuReply_descriptor,
        new java.lang.String[] { "Hamburger", "Cheeseburger", "Coke", "Fanta", "ResID", });
    internal_static_preorder_OrderRequest_descriptor =
      getDescriptor().getMessageTypes().get(2);
    internal_static_preorder_OrderRequest_fieldAccessorTable = new
      com.google.protobuf.GeneratedMessageV3.FieldAccessorTable(
        internal_static_preorder_OrderRequest_descriptor,
        new java.lang.String[] { "Food", "Drink", "Qty", });
    internal_static_preorder_OrderReply_descriptor =
      getDescriptor().getMessageTypes().get(3);
    internal_static_preorder_OrderReply_fieldAccessorTable = new
      com.google.protobuf.GeneratedMessageV3.FieldAccessorTable(
        internal_static_preorder_OrderReply_descriptor,
        new java.lang.String[] { "OrderNo", "TotalPrice", "Message", });
    internal_static_preorder_StatusRequest_descriptor =
      getDescriptor().getMessageTypes().get(4);
    internal_static_preorder_StatusRequest_fieldAccessorTable = new
      com.google.protobuf.GeneratedMessageV3.FieldAccessorTable(
        internal_static_preorder_StatusRequest_descriptor,
        new java.lang.String[] { "OrderNo", });
    internal_static_preorder_StatusReply_descriptor =
      getDescriptor().getMessageTypes().get(5);
    internal_static_preorder_StatusReply_fieldAccessorTable = new
      com.google.protobuf.GeneratedMessageV3.FieldAccessorTable(
        internal_static_preorder_StatusReply_descriptor,
        new java.lang.String[] { "Status", });
  }

  // @@protoc_insertion_point(outer_class_scope)
}
