// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: preorder.proto

package grpc.ca.preorder;

public interface StatusReplyOrBuilder extends
    // @@protoc_insertion_point(interface_extends:preorder.StatusReply)
    com.google.protobuf.MessageOrBuilder {

  /**
   * <code>string Status = 1;</code>
   */
  java.lang.String getStatus();
  /**
   * <code>string Status = 1;</code>
   */
  com.google.protobuf.ByteString
      getStatusBytes();
}
