// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: preorder.proto

package grpc.ca.preorder;

public interface StatusRequestOrBuilder extends
    // @@protoc_insertion_point(interface_extends:preorder.StatusRequest)
    com.google.protobuf.MessageOrBuilder {

  /**
   * <code>int32 orderNo = 1;</code>
   */
  int getOrderNo();
}
